version: "3"

services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    volumes:
      - /home/sasori/Documents/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootkit
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - wordpress_db
    networks:
      - wp
  wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootkit
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
    volumes:
      - /home/sasori/Documents/mariaDB:/var/lib/mysql
    networks:
      - wp
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: wordpress_db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootkit
    depends_on:
      - wordpress_db
    networks:
      - wp

networks:
  wp:
